version: 3.0.{build}
branches:
  only:
  - master
configuration: Release
platform: Any CPU
clone_folder: C:\Projects\DMOAdvancedLauncher
install:
- choco install InnoSetup
- set PATH=%PATH%;"C:\Program Files (x86)\Inno Setup 5"
build:
  project: AdvancedLauncher.sln
  verbosity: minimal
after_build:
- echo "Running Inno Setup:"
- iscc Shared\setup_project.iss
- dir Shared\Installer
artifacts:
- path: '\Shared\Installer\DMOAdvancedLauncher_install.exe'
  name: DMOAdvancedLauncher_install