version: 3.3.{build}
branches:
  only:
  - master
os: Visual Studio 2015
configuration: Release
platform: Any CPU
clone_folder: C:\Projects\DMOAdvancedLauncher
assembly_info:
  patch: true
  file: AdvancedLauncher\Properties\AssemblyInfo.cs
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
install:
- choco install InnoSetup
- choco install doxygen.install 
- set PATH=%PATH%;"C:\Program Files (x86)\Inno Setup 5"
- set PATH=%PATH%;"C:\Program Files\doxygen\bin"
- set PATH=%PATH%;"C:\Program Files (x86)\doxygen\bin"
- set PATH="C:\Program Files (x86)\MSBuild\14.0\Bin";%PATH% 
- set DOXYGEN_PROJECT_DIR=C:\Projects\DMOAdvancedLauncher\AdvancedLauncherSDK
before_build:
- ps: ./DecryptReleaseKey.ps1
- git submodule update --init --recursive
- nuget restore
build:
  project: AdvancedLauncher.sln
  verbosity: minimal
after_build:
- echo "Running Inno Setup:"
- iscc Shared\setup_project.iss
- doxygen.exe "%DOXYGEN_PROJECT_DIR%\Doxyfile"
test: off
artifacts:
- path: '\Shared\Installer\DMOAdvancedLauncher_install.exe'
  name: DMOAdvancedLauncher_install
- path: '\AdvancedLauncherSDK\bin\Release'
  name: AdvancedLauncherSDK
  type: zip
deploy:
- provider: GitHub
  tag: v$(appveyor_build_version)
  release: DMO Advanced Launcher v$(appveyor_build_version)
  auth_token:
    secure: n5D3B3H3/G24ynE9Nkuta8a5Oeyzh+f2W05DKaoFgBpQaubZTIz6YWmOeI917fnc
  artifact: DMOAdvancedLauncher_install
  draft: true
  prerelease: true