var namespace_advanced_launcher_1_1_s_d_k_1_1_model_1_1_events_1_1_proxy =
[
    [ "BaseEventProxy", "class_advanced_launcher_1_1_s_d_k_1_1_model_1_1_events_1_1_proxy_1_1_base_event_proxy.html", "class_advanced_launcher_1_1_s_d_k_1_1_model_1_1_events_1_1_proxy_1_1_base_event_proxy" ],
    [ "ConfigurationChangedProxy", "class_advanced_launcher_1_1_s_d_k_1_1_model_1_1_events_1_1_proxy_1_1_configuration_changed_proxy.html", "class_advanced_launcher_1_1_s_d_k_1_1_model_1_1_events_1_1_proxy_1_1_configuration_changed_proxy" ],
    [ "EventProxy", "class_advanced_launcher_1_1_s_d_k_1_1_model_1_1_events_1_1_proxy_1_1_event_proxy.html", "class_advanced_launcher_1_1_s_d_k_1_1_model_1_1_events_1_1_proxy_1_1_event_proxy" ]
];